version: '3.8'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
    ports:
      - "9501:9501" # Swoole WebSocket 端口
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_app
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    ports:
      - "8080:80" # 監聽 HTTP 請求

  redis:
    image: redis:alpine
    container_name: redis_app
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
